package com.gobinda.connection.api

 const val PICK_ROOM_TIMEOUT = 5000L
 const val SEND_OFFER_TIMEOUT = 5000L
 const val RECEIVE_OFFER_TIMEOUT = 20000L
 const val SEND_ANSWER_TIMEOUT = 5000L
 const val RECEIVE_ANSWER_TIMEOUT = 10000L
 const val SEND_ICE_TIMEOUT = 5000L
 const val RECEIVE_ICE_TIMEOUT = 5000L
 const val ICE_CANDIDATES_GENERATE_TIMEOUT = 5000L
 const val CONNECTION_CONFIRMATION_TIMEOUT = 5000L